### ISSUE TITLE
Skin Error

### ISSUE THREAD

**Issue by ItsMyLifeForce** [MOXHAFOREVA/mx-multicharacter#11]
Some Skin error, i edit the skin script, this is 2.0

![neww](https://user-images.githubusercontent.com/89754582/131270450-f9957c4a-6bd0-4f56-95c2-7409d8c642cf.jpg)

**Comment by JemishMalaviya** [comment]
> Some Skin error, i edit the skin script, this is 2.0
> 
> ![neww](https://user-images.githubusercontent.com/89754582/131270450-f9957c4a-6bd0-4f56-95c2-7409d8c642cf.jpg)

same error

**Comment by MOXHAFOREVA** [comment]
esx_skin does not save on database. It's not about multicharacter.
