### ISSUE TITLE
Secound character prefix index revert on auto save

### ISSUE THREAD

**Issue by HristoKehayov** [MOXHAFOREVA/mx-multicharacter#12]
I love your resource and thank you for sharing it with us. So i am using extendedmode v1.2. When i create my second character it gets create with the prefix Char2steam:xxxx but after the automatic save it gets reverted back to steam:xxxx and i think this messes things up with last_character and inventory doesnt gets save properly because it created new user with id: steam:xxxxx and new inventory
![Screenshot from 2021-09-02 22-24-45](https://user-images.githubusercontent.com/17788920/131904274-09172cb6-bde2-405c-ab0d-4acdeb56f00a.png)
![Screenshot from 2021-09-02 22-25-04](https://user-images.githubusercontent.com/17788920/131904281-5ab7f79f-66a1-45f7-80cb-33b8008f2615.png)

**Comment by MOXHAFOREVA** [comment]
Check the config identifier tables. Add the sql tables you use separately there.

**Comment by HristoKehayov** [comment]
I already did this. I have added all of the tables containing either owner or identifier.  I dont think that is the problem.

**Comment by MOXHAFOREVA** [comment]
If it goes back to normal when you log into the game, it's perfectly normal. Other characters remain as char1 char2 etc... and those characters are not saved. I don't understand the problem here?
