### ISSUE TITLE
No cinematic or skin

### ISSUE THREAD

**Issue by dernathan** [MOXHAFOREVA/mx-multicharacter#18]
Hey this is what i currently get using esx legacy

![grafik](https://user-images.githubusercontent.com/1337485/148301923-f139ba2b-2d8d-4d23-a9e3-1c4ed980148d.png)

**Comment by dernathan** [comment]
fixed it now. now after i spawn i get the normal skin changer without cinematic and i spawn in the apartment 
![grafik](https://user-images.githubusercontent.com/1337485/148303600-25386390-2efb-447f-bcf6-93f18c6adfbc.png)

**Comment by MOXHAFOREVA** [comment]
mx-multichar > config set the skinnothave true

or u can check the code it has a simple trigger

**Comment by SelfishEagle** [comment]
> fixed it now. now after i spawn i get the normal skin changer without cinematic and i spawn in the apartment ![grafik](https://user-images.githubusercontent.com/1337485/148303600-25386390-2efb-447f-bcf6-93f18c6adfbc.png)

how did you fix this please?

**Comment by MOXHARTZ** [comment]
Trigger the  cinematic animation event manually
