### ISSUE TITLE
how can i fix this (i put screenshot links, click on the links to see the image of the issues)

### ISSUE THREAD

**Issue by InfinityBg** [MOXHAFOREVA/mx-multicharacter#19]
[image](https://i.imgur.com/LBp5onX.png)
[image](https://i.imgur.com/PKTjqcx.png)
[img]https://i.imgur.com/LBp5onX.png[/img]
[img]https://i.imgur.com/PKTjqcx.png[/img]

**Comment by MOXHARTZ** [comment]
Config > essentialmode = true
