### ISSUE TITLE
Spawning

### ISSUE THREAD

**Issue by icecubepiso** [MOXHAFOREVA/mx-multicharacter#2]
Hello, is there any way, how to get peopel spawn **only** at last location.. i mean witouth that UI. Cuze 1) it's killing the person, before he select and 2) peopel just combat loging and spawn at different location.

**Comment by MOXHAFOREVA** [comment]
![image](https://user-images.githubusercontent.com/70913098/126637762-2fe8027e-daec-44d8-9b78-77fe1c2c9550.png)

Delete > 

<div class="spawnlocation" data-name="airport">
                    <i class="fas fa-map-marker-alt fa-2x"></i>
               </div>
               <div class="spawnlocation" data-name="paleto">
                    <i class="fas fa-map-marker-alt fa-2x"></i>
               </div>
               <div class="spawnlocation" data-name="police">
                    <i class="fas fa-map-marker-alt fa-2x"></i>
    </div>
