### ISSUE TITLE
event not safe for net

### ISSUE THREAD

**Issue by BTNGaming** [MOXHAFOREVA/mx-multicharacter#3]
[  script:es_extended] event esx:onPlayerJoined was not safe for net

I'm running on esx legacy with linden inventory etc etc.

This is the only error i receive currently, BUT this happens...

https://i.imgur.com/0N27Qvv.png
https://i.imgur.com/OewUrBj.jpg
https://i.imgur.com/Inhn2M9.jpg

Said loading story mode and never gets passed that screen.

Followed your instructions to the letter, I hear the airport and such when I make my character, but I do NOT see anything more than the "Story mode loading" message and background.

**Comment by BTNGaming** [comment]
Tried on a vanilla server as well, no luck.

**Comment by BTNGaming** [comment]
Still haven't heard a word dude... I'm going to go ahead and have ESX Shut down the post then, as we developers don't need a million people DM'ing me and other devs to fix YOUR work that isn't working.

**Comment by thelindat** [comment]
`Config.Multichar = false` and
```lua
	RegisterNetEvent('esx:onPlayerJoined')
	AddEventHandler('esx:onPlayerJoined', function(cid, data)
```
on the server?

**Comment by icecubepiso** [comment]
There is no way, this thing will work :D he need to like use whole different edit for your legacy.. and he sending it to me..

**Comment by Grogyas** [comment]
Same issue

**Comment by MOXHAFOREVA** [comment]
The solution has already been given above. 

```
Config.Multichar = false
```

**Comment by 5mLucifer** [comment]
Big shame it doesn't work at all on ESX Legacy. Tried my absolute best to get it to work, however nothing could fix it.
