### ISSUE TITLE
Wrong Last Location & Player dies by reconnecting

### ISSUE THREAD

**Issue by ZaneGunBlade** [MOXHAFOREVA/mx-multicharacter#4]
Hi 
I have an Issue with this script and we dont know how to fix it!
Like said in the Title are joining my Players if there clicking on Last Location, there spawning once in the Grove Street or on the Airport
And everytime a Player joins, this Player dies and becomes a Black & White Screen and we need to revive this Person.

Pls help us. We are a small Server on Five M and were losing Players because of this
Have a Great Day.
Zane

**Comment by MOXHAFOREVA** [comment]
Hi, I'll test it now. If I can find the problem, I will reply.

**Comment by MOXHAFOREVA** [comment]
I just took a look and did not encounter such a problem. Which esx version are you using? Maybe you can send me a base to test.

**Comment by ZaneGunBlade** [comment]
We are using Plume ESX

**Comment by ZaneGunBlade** [comment]
With the extended Legacy (Thats what my Delevoper said)

**Comment by MOXHAFOREVA** [comment]
I cannot solve the problem when I do not see the problem. I can help if you send me your own server in base form.
