### ISSUE TITLE
Can't make character

### ISSUE THREAD

**Issue by TheShadowPL** [MOXHAFOREVA/mx-multicharacter#6]
when showing me character selector i can't create new character
I'm using:
es_extended 1.1.0
essentialmode 6.2.2
skinchanger from your resposittory
db wiped 
![image](https://user-images.githubusercontent.com/39172218/129444913-d3fda50f-f570-4285-9ebe-7c32555446da.png)
![image](https://user-images.githubusercontent.com/39172218/129444909-1d3f78e2-54cf-4c27-a02e-b11ad8525268.png)

**Comment by MOXHAFOREVA** [comment]
What is the identifier value on the config?

![image](https://user-images.githubusercontent.com/70913098/129445131-e77462d8-f7bc-497d-b6d9-d1af1755b08b.png)

**Comment by TheShadowPL** [comment]
Identifier = 'license',

**Comment by MOXHAFOREVA** [comment]
It should be steam for you but I don't think that's your fault

**Comment by TheShadowPL** [comment]
Thanks for help <3 now everything works fine now

**Comment by TheShadowPL** [comment]
Hi still i have problem but now when i joned to the serwer and choose character then position i spawned under map and get this errors
![image](https://user-images.githubusercontent.com/39172218/129478791-4f1b1cd1-58b1-40ae-bc32-1d4966cca160.png)
![image](https://user-images.githubusercontent.com/39172218/129478798-212bda97-4112-419d-9a69-59df53b23120.png)

**Comment by MOXHAFOREVA** [comment]
Reinstall mx-spawn
