### ISSUE TITLE
Error when selecting character

### ISSUE THREAD

**Issue by Grogyas** [MOXHAFOREVA/mx-multicharacter#7]
I got this error when selecting character

I am using Linden's ESX Legacy

![image](https://user-images.githubusercontent.com/48384565/129795134-98fecf42-9216-41cf-b976-c512bcfbdca5.png)

**Comment by MOXHAFOREVA** [comment]
Hey, sorry idk how the error happened. The error value is a static value on the html.

**Comment by Grogyas** [comment]
Ok, FiveM is really fucked. It fixed itself somehow
