### ISSUE TITLE
Character Dont Get Saved

### ISSUE THREAD

**Issue by LoyaltyDeadShot** [MOXHAFOREVA/mx-multicharacter#9]
I follow all the instructions, I create my character and I log out and log in and my character dont get safe when I re-logging but it saves himself on the data base users as char1 char2 char3 idk what to do please help. Sorry for my bad english btw

**Comment by LoyaltyDeadShot** [comment]
Btw Im using Esx 1.2

**Comment by LoyaltyDeadShot** [comment]
Its working but the cutscene its not showing up for some reason

**Comment by LoyaltyDeadShot** [comment]
![image](https://user-images.githubusercontent.com/79301037/130016397-9f7f5ea8-33a6-447a-8092-a132c6a785fc.png)

this is showing up

**Comment by LoyaltyDeadShot** [comment]
I need to make my character two times in order to save it

**Comment by LoyaltyDeadShot** [comment]
![image](https://user-images.githubusercontent.com/79301037/130021268-988b6723-5810-4eec-b127-fd73fd3185b3.png)
![image](https://user-images.githubusercontent.com/79301037/130021388-1948bd6d-7d8a-4328-9d68-035a63dd91da.png)
In the database it shows off that but ig it shows up like i dont have character plus in the console shows up this
![image](https://user-images.githubusercontent.com/79301037/130021490-b3b725d4-9b76-4f03-89f4-d17fb918d97b.png)

**Comment by MOXHAFOREVA** [comment]
Remove identifier primary key

**Comment by LoyaltyDeadShot** [comment]
> Remove identifier primary key

So I remove it from the users and datastore or only the datastore ? That should fix the cutscene as well ?

**Comment by LoyaltyDeadShot** [comment]
![image](https://user-images.githubusercontent.com/79301037/130099771-edd459ee-386e-460a-8d48-17632e8a2fe2.png)
this is showing up and it doesnt make the scenecut

**Comment by MOXHAFOREVA** [comment]
Remove all. And to set the cutscene, review the appropriate config and set the skinnothave to true.

**Comment by LoyaltyDeadShot** [comment]
its working all except the character saving

**Comment by gunsela92** [comment]
Same problem. Im using linden's es_extended and not saving the characters after filling the character information. And after loading screen, it starts to load story mode. It doesnt hide what ever i do.

**Comment by MOXHAFOREVA** [comment]
It's not a bug with multicharacter that you hooked up to story mode. If there is such a mistake, it happens to everyone.

**Comment by gunsela92** [comment]
Its not happening with esx_multicharacter. I think there is a compatibility issue
